---
version: "2.1"
services:
  jekyll:
      image: jekyll/jekyll:latest
      container_name: jekyll
      command: jekyll serve
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll/
      network_mode: "bridge"
      environment: 
        - JEKYLL_GID=101
        - JEKYLL_UID=1024